### PR TITLE
replay stuff fix

### PR DESCRIPTION
**Pull request by Ciallo-Ani**
- fix [error spams](https://pastebin.com/nLGqLefa) if no ticks.
- fix not gonna ignore triggers
- can't help renaming something

### CODE REVIEW

**Comment by tslashd** [comment]
I don't even know how to reproduce the issue that this was causing so I will leave to someone else to test out

@Ciallo-Ani believe it was you who reworked the replays some time ago, do you think this is doable? #387

**Comment by tslashd** [comment]
Okay I will try and get these things tested:
1. Saving new replay for stage, bonus, map does **NOT** error out
2. Replaying said record does **NOT** error out
3. Replaying an existing record does **NOT** error out
4. Leaving the server after replaying **3** or **4** does **NOT** error out

And will reply here with results :)

@Ciallo-Ani
Let me know if you think of anything else to test regarding the _PR_

**Comment by freakexeuLow** [comment]
was tested and the same error comes on the same map

L 06/07/2022 - 16:09:52: SourceMod error session started
L 06/07/2022 - 16:09:52: Info (map "surf_polski_sklep") (file "/home/user2-6/server/csgo/csgo/addons/sourcemod/logs/errors_20220607.log")
L 06/07/2022 - 16:09:52: [SM] Exception reported: Invalid index 0 (count: 0)
L 06/07/2022 - 16:09:52: [SM] Blaming: surftimer/SurfTimer.smx
L 06/07/2022 - 16:09:52: [SM] Call stack trace:
L 06/07/2022 - 16:09:52: [SM]   [0] ArrayList.GetArray
L 06/07/2022 - 16:09:52: [SM]   [1] Line 969, surftimer/replay.sp::Replay_Playback
L 06/07/2022 - 16:09:52: [SM]   [2] Line 996, surftimer/hooks.sp::OnPlayerRunCmd
L 06/07/2022 - 16:09:52: [SM] Exception reported: Invalid index 0 (count: 0)
L 06/07/2022 - 16:09:52: [SM] Blaming: surftimer/SurfTimer.smx
L 06/07/2022 - 16:09:52: [SM] Call stack trace:
L 06/07/2022 - 16:09:52: [SM]   [0] ArrayList.GetArray
L 06/07/2022 - 16:09:52: [SM]   [1] Line 969, surftimer/replay.sp::Replay_Playback
L 06/07/2022 - 16:09:52: [SM]   [2] Line 996, surftimer/hooks.sp::OnPlayerRunCmd

**Comment by tslashd** [comment]
> Okay I will try and get these things tested:
> 
> 1. Saving new replay for stage, bonus, map does **NOT** error out
> 2. Replaying said record does **NOT** error out
> 3. Replaying an existing record does **NOT** error out
> 4. Leaving the server after replaying **3** or **4** does **NOT** error out

1 = True
2 = True
3 = True
4 = True (both cases)

Tried on the same map _surf_polski_sklep_ and had no errors, @freakexeuLow i cannot reproduce it on that same map
for bonus I used _surf_guitar_hi_


_.rec files for said replays attached in the zip_
[pr_replays.zip](https://github.com/surftimer/SurfTimer/files/8855220/pr_replays.zip)

**Review by Bara — APPROVED** [review]

**Pull request merged**
