### PR TITLE
CSD fix 

### LINKED ISSUE #349: Centerspeed Display for replays are inaccurate
**Describe the bug**
The Centerspeed Display for replays is showing the wrong speed

**Expected behavior**
Should show the same speed as the Center HUD or the same speed as in run.

**Screenshots**
unknown

**Plugin List**
  01 "Client Preferences" (1.10.0.6516) by AlliedModders LLC
  02 "Nextmap" (1.10.0.6516) by AlliedModders LLC
  03 "Basic Info Triggers" (1.10.0.6516) by AlliedModders LLC
  04 "Fun Votes" (1.10.0.6516) by AlliedModders LLC
  05 "SourceBans++: SourceComms" (1.6.4) by Alex, SourceBans++ Dev Team
  06 "SurfTimer Rock The Vote" (1.8.3) by AlliedModders LLC & SurfTimer Contributors
  07 "Sound Commands" (1.10.0.6516) by AlliedModders LLC
  08 "SourceBans++: Main Plugin" (1.6.4) by SourceBans Development Team, SourceBans++ Dev Team
  09 "[Surf Timer] Teleport Destination Finder" (1.0) by marcowmadeira
  10 "SurfTimer Nominations" (1.8.3) by AlliedModders LLC & SurfTimer Contributors
  11 "SurfTimer MapChooser" (1.8.3) by AlliedModders LLC & SurfTimer Contributors
  12 "SourceBans++: SourceSleuth" (1.6.4) by ecca, SourceBans++ Dev Team
  13 "Basic Commands" (1.10.0.6516) by AlliedModders LLC
  14 "Discord API" (0.1.97) by Deathknife
  15 "SourceBans++ Report Plugin" (1.6.4) by RumbleFrog, SourceBans++ Dev Team
  16 "RNGFix" (1.1.2) by rio
  17 "Momentum surf fix '2" (1.1.3) by GAMMA CASE
  18 "Anti-Flood" (1.10.0.6516) by AlliedModders LLC
  19 "Normalized Run Speed" (0.6) by sneaK
  20 "Basic Chat" (1.10.0.6516) by AlliedModders LLC
  21 "Admin File Reader" (1.10.0.6516) by AlliedModders LLC
  22 "Admin Menu" (1.10.0.6516) by AlliedModders LLC
  23 "Basic Comm Control" (1.10.0.6516) by AlliedModders LLC
  24 "SourceBans++: Admin Config Loader" (1.6.4) by AlliedModders LLC, SourceBans++ Dev Team
  25 "SourceBans++: Bans Checker" (1.6.4) by psychonic, Ca$h Munny, SourceBans++ Dev Team
  26 "Paint!" (2.0) by SlidyBat
  27 "Player Commands" (1.10.0.6516) by AlliedModders LLC
  28 "Reserved Slots" (1.10.0.6516) by AlliedModders LLC
  29 "SurfTimer" (1.0.3) by Ace & olokos
  30 "Server redirect" (1.3.1) by GAMMA CASE
  31 "CS:GO Movement Unlocker" (1.0) by Peace-Maker
  32 "Fun Commands" (1.10.0.6516) by AlliedModders LLC
  33 "Basic Votes" (1.10.0.6516) by AlliedModders LLC
  34 "Admin Help" (1.10.0.6516) by AlliedModders LLC
  35 "SurfTimer Vote Extend" (1.8.3) by SurfTimer Contributors

**Additional context**
Was recreateable even on a new map with no prior records set and without practice mode ever used.

### PR DESCRIPTION
**Pull request by shipyy**
Sry for closing #421 (im noob at github and fucked everything xD), but i have fixed things after. 
this request has the changes requested in #421 made to it, if anything more needs to be done just tell me :)

Close #349

### CODE REVIEW

**Review by Bara — APPROVED** [review]
I've nothing against this, when it works. So it would be nice when someone can test this before merge.

**Comment by tslashd** [comment]
> I've nothing against this, when it works. So it would be nice when someone can test this before merge.

I could try testing this out later today and reply here

**Comment by tslashd** [comment]
So I did some testing and the only thing that I found is that when you change the `Speed Mode` to be different from `XY`, none of the colours work (it stays on `WHITE`) and `MOMENTUM` gradient does not work as well.

Not a big issue imo but others need to give their opinion on it as well.

**Comment by shipyy** [comment]
i believe i canf fix that

**Review by DaLLuZZ — APPROVED** [review]

**Pull request merged**
