### PR TITLE
fix for mysql timeout

### PR DESCRIPTION
**Pull request by shipyy**
#469
this seems to have fixed it for me, but ya never know xD

### CODE REVIEW

**Comment by tslashd** [comment]
```
L 07/10/2022 - 11:12:44: [SM] Exception reported: Error fetching data from field 1
L 07/10/2022 - 11:12:44: [SM] Blaming: SurfTimer.smx
L 07/10/2022 - 11:12:44: [SM] Call stack trace:
L 07/10/2022 - 11:12:44: [SM]   [0] SQL_FetchString
L 07/10/2022 - 11:12:44: [SM]   [1] Line 202, surftimer\db\updater.sp::SQLCheckDataType
L 07/10/2022 - 11:12:44: [SM] Exception reported: More/Less then 1 rows? RowCount: 0, Table: ck_checkpoints, Column: cp2
L 07/10/2022 - 11:12:44: [SM] Blaming: SurfTimer.smx
L 07/10/2022 - 11:12:44: [SM] Call stack trace:
L 07/10/2022 - 11:12:44: [SM]   [0] SetFailState
L 07/10/2022 - 11:12:44: [SM]   [1] Line 194, surftimer\db\updater.sp::SQLCheckDataType
```

image


I do not understand why it's looking for `cp2` when the whole point of testing this is to remove `cpX` columns and move them into `cp` only

**Comment by tslashd** [comment]
DB seems to now be converted by the plugin without any timeouts.
After joining the server though your timer does not start, nor does it get updated when switching between stages.

DB used for this was `cp1, cp2, cp3, ...` format with `FLOAT` values.

Server console first run:
```
Converting ck_bonus-runtime to decimal(10, 4)...
Converting ck_checkpoints-cp1 to decimal(10, 4)...
Converting ck_checkpoints-cp2 to decimal(10, 4)...
Converting ck_checkpoints-cp3 to decimal(10, 4)...
Converting ck_checkpoints-cp4 to decimal(10, 4)...
Converting ck_checkpoints-cp5 to decimal(10, 4)...
Converting ck_checkpoints-cp6 to decimal(10, 4)...
Converting ck_checkpoints-cp7 to decimal(10, 4)...
Converting ck_checkpoints-cp8 to decimal(10, 4)...
Converting ck_checkpoints-cp9 to decimal(10, 4)...
Converting ck_checkpoints-cp10 to decimal(10, 4)...
Converting ck_checkpoints-cp11 to decimal(10, 4)...
Converting ck_checkpoints-cp12 to decimal(10, 4)...
Converting ck_checkpoints-cp13 to decimal(10, 4)...
Converting ck_checkpoints-cp14 to decimal(10, 4)...
Converting ck_checkpoints-cp15 to decimal(10, 4)...
Converting ck_checkpoints-cp16 to decimal(10, 4)...
Converting ck_checkpoints-cp17 to decimal(10, 4)...
Converting ck_checkpoints-cp18 to decimal(10, 4)...
Converting ck_checkpoints-cp19 to decimal(10, 4)...
Converting ck_checkpoints-cp20 to decimal(10, 4)...
Converting ck_checkpoints-cp21 to decimal(10, 4)...
Converting ck_checkpoints-cp22 to decimal(10, 4)...
Converting ck_checkpoints-cp23 to decimal(10, 4)...
Converting ck_checkpoints-cp24 to decimal(10, 4)...
Converting ck_checkpoints-cp25 to decimal(10, 4)...
Converting ck_checkpoints-cp26 to decimal(10, 4)...
Converting ck_checkpoints-cp27 to decimal(10, 4)...
Converting ck_checkpoints-cp28 to decimal(10, 4)...
Converting ck_checkpoints-cp29 to decimal(10, 4)...
Converting ck_checkpoints-cp30 to decimal(10, 4)...
Converting ck_checkpoints-cp31 to decimal(10, 4)...
Converting ck_checkpoints-cp32 to decimal(10, 4)...
Converting ck_checkpoints-cp33 to decimal(10, 4)...
Converting ck_checkpoints-cp34 to decimal(10, 4)...
Converting ck_checkpoints-cp35 to decimal(10, 4)...
Converting ck_latestrecords-runtime to decimal(10, 4)...
Converting ck_playertemp-runtimeTmp to decimal(10, 4)...
Converting ck_playertimes-runtimepro to decimal(10, 4)...
Connection to Steam servers successful.
```

A couple of seconds later:
```
Converting ck_bonus-runtime to decimal(12, 6)...
Converting ck_checkpoints-cp1 to decimal(12, 6)...
Converting ck_checkpoints-cp2 to decimal(12, 6)...
Converting ck_checkpoints-cp3 to decimal(12, 6)...
Converting ck_checkpoints-cp4 to decimal(12, 6)...
Converting ck_checkpoints-cp5 to decimal(12, 6)...
Converting ck_checkpoints-cp6 to decimal(12, 6)...
Converting ck_checkpoints-cp7 to decimal(12, 6)...
Converting ck_checkpoints-cp8 to decimal(12, 6)...
Converting ck_checkpoints-cp9 to decimal(12, 6)...
Converting ck_checkpoints-cp10 to decimal(12, 6)...
Converting ck_checkpoints-cp11 to decimal(12, 6)...
Converting ck_checkpoints-cp12 to decimal(12, 6)...
Converting ck_checkpoints-cp13 to decimal(12, 6)...
Converting ck_checkpoints-cp14 to decimal(12, 6)...
Converting ck_checkpoints-cp15 to decimal(12, 6)...
Converting ck_checkpoints-cp16 to decimal(12, 6)...
Converting ck_checkpoints-cp17 to decimal(12, 6)...
Converting ck_checkpoints-cp18 to decimal(12, 6)...
Converting ck_checkpoints-cp19 to decimal(12, 6)...
Converting ck_checkpoints-cp20 to decimal(12, 6)...
Converting ck_checkpoints-cp21 to decimal(12, 6)...
Converting ck_checkpoints-cp22 to decimal(12, 6)...
Converting ck_checkpoints-cp23 to decimal(12, 6)...
Converting ck_checkpoints-cp24 to decimal(12, 6)...
Converting ck_checkpoints-cp25 to decimal(12, 6)...
Converting ck_checkpoints-cp26 to decimal(12, 6)...
Converting ck_checkpoints-cp27 to decimal(12, 6)...
Converting ck_checkpoints-cp28 to decimal(12, 6)...
Converting ck_checkpoints-cp29 to decimal(12, 6)...
Converting ck_checkpoints-cp30 to decimal(12, 6)...
Converting ck_checkpoints-cp31 to decimal(12, 6)...
Converting ck_checkpoints-cp32 to decimal(12, 6)...
Converting ck_checkpoints-cp33 to decimal(12, 6)...
Converting ck_checkpoints-cp34 to decimal(12, 6)...
Converting ck_checkpoints-cp35 to decimal(12, 6)...
Converting ck_latestrecords-runtime to decimal(12, 6)...
Converting ck_playertemp-runtimeTmp to decimal(12, 6)...
Converting ck_playertimes-runtimepro to decimal(12, 6)...
Converting ck_wrcps-runtimepro to decimal(12, 6)...
```

**Comment by tslashd** [comment]
can confirm it's actually fixed

**Comment by coverrt** [comment]
This timeout could be related to the database `max_execution_time` system variable.

https://mariadb.com/kb/en/aborting-statements/

**Comment by dPexxIAM** [comment]
@tslashd @shipyy so this should be merged yes? you've confirmed it fixes https://github.com/surftimer/SurfTimer/issues/469

**Comment by shipyy** [comment]
@dPexxIAM yup, no longer had any issue related to timeouts

**Review by dPexxIAM — APPROVED** [review]

**Comment by tslashd** [comment]
> max_execution_time


Don't think so
image


It's fixed now anyway. 😄

**Pull request merged**
