### PR TITLE
fix for #524

### PR DESCRIPTION
**Pull request by shipyy**
previous pr fix for this in hindsifghted i believe was missing a few more things (til)

* fix for wrong PERSONAL record query
* fix for wrong position to send new record forward

### CODE REVIEW

**Comment by shipyy** [comment]
i have not tested it (cannot atm) if someone else could confirm it does in fact work would be awesome! (:

**Comment by Synert** [comment]
Style times are saving properly, but records are not being output in the Discord or printing the record message (<player> beat the <style> map record). This is also occurring for the first time set

**Review by Synert — CHANGES_REQUESTED** [review]
Typo in surftimer.phrases.txt - '{4,s}' -> '{4:s}'. Other changes confirmed working on Thunderdome

**Comment by shipyy** [comment]
hopefully all good now (:

**Review by Synert — APPROVED** [review]
Tested and working as expected on Thunderdome

**Review by dPexxIAM — APPROVED** [review]

**Pull request merged**
