### PR TITLE
Stage sm_startpos

### PR DESCRIPTION
**Pull request by shipyy**
Allows players to use the cmd ```sm_startpos``` in stage zones

### CODE REVIEW

**Comment by DaLLuZZ** [comment]
This will lead to lots of cheating srcp times on many stages on so many maps...

**Comment by tslashd** [comment]
Yeah using this would make stage records more abusable than they currently are (staged linears like ace)

Would have to use maybe prac timer when doing a stage after using `sm_startpos` imo

**Comment by shipyy** [comment]
@DaLLuZZ @tslashd i made so u can only use startpos for stages when not in a run

**Comment by DaLLuZZ** [comment]
Do you have a test server?

**Comment by shipyy** [comment]
locally xd

**Comment by tslashd** [comment]
> @DaLLuZZ @tslashd i made so u can only use startpos for stages when not in a run

So when you're in a map run will you get teleported to the default stage spawn or wherever you've set your `startpos` for the given stage?

**Comment by shipyy** [comment]
if u are in a run u will teleported to the default stage position

**Comment by shipyy** [comment]
im asuming u mean like using "sm_rs" during a run? because ye i did take that into account :D

**Review by dPexxIAM — APPROVED** [review]
ty

**Pull request merged**
