### PR TITLE
Increase name length

### LINKED ISSUE #532: [BUG] Data too long for column 'name' at row 1
**Describe the bug**

L 10/02/2022 - 03:09:37: SourceMod error session started
L 10/02/2022 - 03:09:37: Info (map "surf_calycate2") (file "/srv/Server-Files/SURF/SURF1-2/csgo/addons/sourcemod/logs/errors_20221002.log")
L 10/02/2022 - 03:09:37: [SurfTimer.smx] [SurfTimer] SQL Error (SQL_CheckCallback): Data too long for column 'name' at row 1
L 10/02/2022 - 03:09:37: [SurfTimer.smx] [SurfTimer] SQL Error (SQL_CheckCallback): Data too long for column 'name' at row 1
L 10/02/2022 - 03:20:37: [SurfTimer.smx] [SurfTimer] SQL Error (SQL_UpdateRecordProCallback): Data too long for column 'name' at row 1
L 10/02/2022 - 03:23:20: [SurfTimer.smx] [SurfTimer] SQL Error (sql_updatePlayerRankPointsCallback): Data too long for column 'name' at row 1
L 10/02/2022 - 03:24:27: [SurfTimer.smx] [SurfTimer] SQL Error (SQL_UpdateRecordProCallback): Data too long for column 'name' at row 1
L 10/02/2022 - 03:25:32: [SurfTimer.smx] [SurfTimer] SQL Error (SQL_UpdateRecordProCallback): Data too long for column 'name' at row 1
L 10/02/2022 - 03:30:41: [SurfTimer.smx] [SurfTimer] SQL Error (sql_updatePlayerRankPointsCallback): Data too long for column 'name' at row 1
L 10/02/2022 - 03:31:40: [SurfTimer.smx] [SurfTimer] SQL Error (SQL_UpdateRecordProCallback): Data too long for column 'name' at row 1
L 10/02/2022 - 03:32:54: [SurfTimer.smx] [SurfTimer] SQL Error (sql_updatePlayerRankPointsCallback): Data too long for column 'name' at row 1
L 10/02/2022 - 03:36:03: Error log file session closed.
L 10/02/2022 - 18:41:04: SourceMod error session started
L 10/02/2022 - 18:41:04: Info (map "surf_andromeda") (file "/srv/Server-Files/SURF/SURF1-2/csgo/addons/sourcemod/logs/errors_20221002.log")
L 10/02/2022 - 18:41:04: [SurfTimer.smx] [SurfTimer] SQL Error (SQL_CheckCallback): Data too long for column 'name' at row 1
L 10/02/2022 - 18:41:04: [SurfTimer.smx] [SurfTimer] SQL Error (SQL_CheckCallback): Data too long for column 'name' at row 1
L 10/02/2022 - 18:44:31: [SurfTimer.smx] [SurfTimer] SQL Error (sql_updatePlayerRankPointsCallback): Data too long for column 'name' at row 1
L 10/02/2022 - 18:46:52: [SurfTimer.smx] [SurfTimer] SQL Error (SQL_UpdateRecordProCallback): Data too long for column 'name' at row 1
L 10/02/2022 - 19:10:44: Error log file session closed.
L 10/02/2022 - 23:26:28: SourceMod error session started
L 10/02/2022 - 23:26:28: Info (map "surf_ivory") (file "/srv/Server-Files/SURF/SURF1-2/csgo/addons/sourcemod/logs/errors_20221002.log")
L 10/02/2022 - 23:26:28: [SurfTimer.smx] [SurfTimer] SQL Error (SQL_CheckCallback): Data too long for column 'name' at row 1
L 10/02/2022 - 23:26:28: [SurfTimer.smx] [SurfTimer] SQL Error (SQL_CheckCallback): Data too long for column 'name' at row 1
L 10/02/2022 - 23:26:28: [SurfTimer.smx] [SurfTimer] SQL Error (SQL_CheckCallback): Data too long for column 'name' at row 1
L 10/02/2022 - 23:26:29: [SurfTimer.smx] [SurfTimer] SQL Error (SQL_CheckCallback): Data too long for column 'name' at row 1
L 10/02/2022 - 23:28:45: [SurfTimer.smx] [SurfTimer] SQL Error (sql_updatePlayerRankPointsCallback): Data too long for column 'name' at row 1
L 10/02/2022 - 23:29:57: [SurfTimer.smx] [SurfTimer] SQL Error (sql_updatePlayerRankPointsCallback): Data too long for column 'name' at row 1
L 10/02/2022 - 23:31:15: Error log file session closed.
L 10/02/2022 - 23:31:42: SourceMod error session started
L 10/02/2022 - 23:31:42: Info (map "surf_hekkz") (file "/srv/Server-Files/SURF/SURF1-2/csgo/addons/sourcemod/logs/errors_20221002.log")
L 10/02/2022 - 23:31:42: [SurfTimer.smx] [SurfTimer] SQL Error (SQL_CheckCallback): Data too long for column 'name' at row 1
L 10/02/2022 - 23:31:42: [SurfTimer.smx] [SurfTimer] SQL Error (SQL_CheckCallback): Data too long for column 'name' at row 1
L 10/03/2022 - 00:01:31: Error log file session closed.

### PR DESCRIPTION
**Pull request by Bara**
Fix #532

### CODE REVIEW

**Comment by KristianP26** [comment]
Something like this is not necessary:
https://gaming.stackexchange.com/questions/301651/diacritics-in-steam-name#:~:text=Note%20that%20your%20profile%20name,using%20that%20%22demon%20text.%22
https://steamcommunity.com/discussions/forum/1/1471967615863282050/
https://www.reddit.com/r/Steam/comments/9yl5dw/nickname_length/
https://www.folkstalk.com/2022/09/steam-max-game-name-length-with-code-examples.html

**Comment by KristianP26** [comment]
https://github.com/surftimer/SurfTimer/issues/532
that will be probably different problem

**Comment by KristianP26** [comment]
I can see the point here because it's a MySQL error, but it will be something else.

**Comment by sneak-it** [comment]
> Something like this is not necessary: https://gaming.stackexchange.com/questions/301651/diacritics-in-steam-name#:~:text=Note%20that%20your%20profile%20name,using%20that%20%22demon%20text.%22 https://steamcommunity.com/discussions/forum/1/1471967615863282050/ https://www.reddit.com/r/Steam/comments/9yl5dw/nickname_length/ https://www.folkstalk.com/2022/09/steam-max-game-name-length-with-code-examples.html

Standard ASCII characters are a single byte, however Steam allows UTF characters and emojis in names which utilize more bytes. Character length != byte size.

From my experience using utf8mb4 collation for storing names, the maximum byte size Steam allows for names is 64 bytes. Bringing the PR varchar size down from 128 to 64 would be appropriate.

**Review by 1zc — APPROVED** [review]

**Pull request merged**
